### ISSUE TITLE
unowned vs weak

### ISSUE THREAD

**Issue by jpalten** [Frugghi/SwiftSH#2] opened 2017-12-07 00:02 UTC
I see a lot of unowned where weak should be used. Would you like me to look into that and create a merge request for that?

**Comment by Frugghi** [comment] 2017-12-08 18:56
If you want to open a PR I'll review it.

If you're referring to the `unowned` in the `DispatchSource` handlers, I don't see how they could be dangerous: if the object that holds the reference to the `DispatchSource` is deallocated, the `DispatchSource` is deallocated too.

**Comment by atticus** [comment] 2018-05-02 02:47
First test of the code, and I'm seeing issues with the unowned references. In the console:

"Fatal error: Attempted to read an unowned reference but object 0x7b480005d780 was already deallocated"

Died in the SSH Queue at

`socketSource.setCancelHandler { [unowned self] in
                self.close()
            }`

**Comment by atticus** [comment] 2018-05-02 04:24
To replicate, the command I was using fell out of scope (wasn't strong reference) before the execute completed. The issue is that instead of the command cleaning up, it took down the app due to a bad unowned pointer. Changing references to weak fixed the issue for me.

**Comment by jpalten** [comment] 2018-06-15 09:37
I created the PR, hope it helps!

**Closed** 2018-06-18 19:43 UTC
